Repository OhMyVector/spotter-vector, pull requests merged in 2021-08, with the labels that each got.

#7 Added Dockerfile
  Dockerfile
Labels: Type: New Feature ➕

#10 Feat: API Structure
  .dockerignore
  Dockerfile
  cmd/api/main.go
  conf.local.yaml
  go.mod
  go.sum
  main.go
  pkg/api/api.go
  pkg/api/websocket/websocket.go
  pkg/common/config/config.go
  pkg/common/server/binding.go
  pkg/common/server/error.go
  pkg/common/server/server.go
  public/index.html
  public/stylesheets/main.css
Labels: Type: New Feature ➕, Type: Refactor 🔨

#12 chg: deps: update echo framework to v4
  go.mod
  go.sum
  pkg/api/websocket/websocket.go
  pkg/common/server/binding.go
  pkg/common/server/error.go
  pkg/common/server/server.go
Labels: Type: Refactor 🔨
